
const sessionKeys = {
    LOCATION_CREATE_RESPONSE: 'LOCATION_CREATE_RESPONSE',
    LOCATION_REQ_BODY: 'LOCATION_REQ_BODY',
    LOCATION_GET_ALL_RESPONSE: 'LOCATION_GET_ALL_RESPONSE'
}
module.exports = sessionKeys;


